### ISSUE TITLE
最新版本总是显示 unknown

### ISSUE THREAD

**Issue by redwolf1996** [kricsleo/vscode-package.json-inspector#1]
如下图所示
<img width="588" alt="unknown" src="https://user-images.githubusercontent.com/9690393/223330908-ded23595-b719-48f1-8a13-2372f9b3acbf.png">

**Comment by kricsleo** [comment]
Could you please run `npm config get registry` in cmd and see what you got? The latest version info depends on your npm registry.
For example, if you got: `https://registry.npmjs.org/` (the default registry), then the latest version is detected from [`https://registry.npmjs.org/lodash/latest`](https://registry.npmjs.org/lodash/latest)

**Comment by redwolf1996** [comment]
> 

thank you . my registry got the third party path so "unknown" appear

**Comment by kricsleo** [comment]
> 

If your registry is self-hosted(as many companies host their own npm registry), you can visit `<your_registry>/lodash/latest` to see if the package info could be fetched. Many self-hosted registries follow this rule. If not, then the latest version info couldn't be fetched.
