### ISSUE TITLE
Support regular expresssion config in settings.json to not fetch data from https://bundlephobia.com

### ISSUE THREAD

**Issue by childrentime** [kricsleo/vscode-package.json-inspector#3]
For some reason, I don't want to expose some package names.

**Comment by kricsleo** [comment]
Thanks for the feedback. Try updating to `v0.2.0` and `'pkg.inspector.disableBundlephobia': string` is available in `.vscode/settings.json` now ;)

(Don't forget to reload VS Code after the settings are changed)
